controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      ros__parameters:
        joints:
          - left_front_hip_joint
          - left_front_knee_joint
          - left_front_ankle_joint

          - right_front_hip_joint
          - right_front_knee_joint
          - right_front_ankle_joint

          - left_rear_hip_joint
          - left_rear_knee_joint
          - left_rear_ankle_joint

          - right_rear_hip_joint
          - right_rear_knee_joint
          - right_rear_ankle_joint
          
        interface_name: position
        command_interfaces:
          - position
        state_interfaces:
          - position
          - velocity
        allow_partial_joints_goal: true
        constraints:
          goal_time: 2.0
          stopped_velocity_tolerance: 0.01
