slam_toolbox:
  ros__parameters:
    use_sim_time: true
    message_filter_queue_size: 100
    use_approximate_sync: true

    slam_mode: "mapping"
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "lidar_link"
    scan_topic: "/scan"
    transform_timeout: 1.0  # hoặc 0.5
    mode: mapping
    debug_logging: true
    transform_timeout: 0.5
    tf_buffer_duration: 30.0
    transform_publish_period: 0.05

    publish_map_frame: true
    map_update_interval: 5.0
    publish_period: 1.0
    resolution: 0.05
    max_laser_range: 8.0
    minimum_time_interval: 0.5

    linear_update: 0.5
    angular_update: 0.5
    temporal_update: 1.0
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2

    use_scan_matching: true
    scan_accumulation: 1
    use_scan_barycenter: false

    loop_closure_enabled: true
    loop_match_min_chain_size: 10
    loop_match_max_distance: 3.0
    loop_match_max_score: 0.3

    serialization_format: "cbor"
    enable_logging: true
    debug_logging: true
