<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="thigh_length" value="0.18" /> <!-- Length of thigh link m -->
  <xacro:property name="shank_length" value="0.18" /> <!-- Length of shank link m -->
  <xacro:property name="motor_mass" value="0.03" /> <!-- Mass of motor links kg -->
  <xacro:property name="motor_radius" value="0.012" /> <!-- Radius of motor cylinders m -->
  <xacro:property name="motor_length" value="0.02" /> <!-- Length of motor cylinders m -->
  <xacro:property name="foot_radius" value="0.03" /> <!-- Radius of foot sphere m -->

  <!-- INERTIAL MACRO -->
  <xacro:macro name="inertial_box_leg" params="mass box_size">
    <inertial>
      <mass value="${mass}" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia
        ixx="${(1/12.0)*mass*(pow(box_size[1],2)+pow(box_size[2],2))}"
        iyy="${(1/12.0)*mass*(pow(box_size[0],2)+pow(box_size[2],2))}"
        izz="${(1/12.0)*mass*(pow(box_size[0],2)+pow(box_size[1],2))}"
        ixy="0.0" ixz="0.0" iyz="0.0" />
    </inertial>
  </xacro:macro>

  <!-- INERTIAL SPHERE MACRO -->
  <xacro:macro name="inertial_sphere" params="mass radius">
    <inertial>
      <mass value="${mass}" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia
        ixx="${(2/5.0)*mass*pow(radius,2)}"
        iyy="${(2/5.0)*mass*pow(radius,2)}"
        izz="${(2/5.0)*mass*pow(radius,2)}"
        ixy="0.0" ixz="0.0" iyz="0.0" />
    </inertial>
  </xacro:macro>

  <!-- LEG MACRO -->
  <xacro:macro name="leg" params="prefix x y">

    <!-- HIP SECTION -->
    <link name="${prefix}_hip_motor">
      <visual>
        <origin xyz="0 0 0" />
        <geometry>
          <cylinder length="${motor_length}" radius="${motor_radius}" />
        </geometry>
        <material name="red" />
      </visual>
      <collision>
        <origin xyz="0 0 0" />
        <geometry>
          <cylinder length="${motor_length}" radius="${motor_radius}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="${motor_mass}" />
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
      </inertial>
    </link>

    <joint name="${prefix}_hip_motor_mount" type="fixed">
      <parent link="chassis" />
      <child link="${prefix}_hip_motor" />
      <origin xyz="${x} ${y} -0.005" rpy="0 0 0" /> <!-- Attach under chassis belly -->
    </joint>

    <joint name="${prefix}_hip_joint" type="revolute">
      <parent link="${prefix}_hip_motor" />
      <child link="${prefix}_thigh" />
      <origin xyz="0 0 0" rpy="0 0.385 0" /> <!-- -45° for thigh backward -->
      <axis xyz="0 1 0" />
      <limit effort="5" velocity="2.0" lower="-1.57" upper="1.57" />
    </joint>

    <link name="${prefix}_thigh">
      <visual>
        <origin xyz="0 0 -${thigh_length/2}" />
        <geometry>
          <box size="0.03 0.03 ${thigh_length}" />
        </geometry>
        <material name="blue" />
      </visual>
      <collision>
        <origin xyz="0 0 -${thigh_length/2}" />
        <geometry>
          <box size="0.03 0.03 ${thigh_length}" />
        </geometry>
      </collision>
      <xacro:inertial_box_leg mass="0.15" box_size="${[0.03, 0.03, thigh_length]}" />
    </link>

    <!-- KNEE SECTION -->
    <link name="${prefix}_knee_motor">
      <visual>
        <origin xyz="0 0 0" />
        <geometry>
          <cylinder length="${motor_length}" radius="${motor_radius}" />
        </geometry>
        <material name="grey" />
      </visual>
      <collision>
        <origin xyz="0 0 0" />
        <geometry>
          <cylinder length="${motor_length}" radius="${motor_radius}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="${motor_mass}" />
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
      </inertial>
    </link>

    <joint name="${prefix}_knee_motor_mount" type="fixed">
      <parent link="${prefix}_thigh" />
      <child link="${prefix}_knee_motor" />
      <origin xyz="0 0 -${thigh_length}" rpy="0 0 0" /> <!-- No rotation here -->
    </joint>

    <joint name="${prefix}_knee_joint" type="revolute">
      <parent link="${prefix}_knee_motor" />
      <child link="${prefix}_shank" />
      <origin xyz="0 0 0" rpy="0 -0.385 0" /> <!-- +45° for shank forward -->
      <axis xyz="0 1 0" />
      <limit effort="5" velocity="2.0" lower="-2.8" upper="0" />
    </joint>

    <link name="${prefix}_shank">
      <visual>
        <origin xyz="0 0 -${shank_length/2}" />
        <geometry>
          <box size="0.02 0.02 ${shank_length}" />
        </geometry>
        <material name="red" />
      </visual>
      <collision>
        <origin xyz="0 0 -${shank_length/2}" />
        <geometry>
          <box size="0.02 0.02 ${shank_length}" />
        </geometry>
      </collision>
      <xacro:inertial_box_leg mass="0.15" box_size="${[0.02, 0.02, shank_length]}" />
    </link>

    <!-- ANKLE SECTION -->
    <link name="${prefix}_ankle_motor">
      <visual>
        <origin xyz="0 0 0" />
        <geometry>
          <cylinder length="${motor_length}" radius="${motor_radius}" />
        </geometry>
        <material name="grey" />
      </visual>
      <collision>
        <origin xyz="0 0 0" />
        <geometry>
          <cylinder length="${motor_length}" radius="${motor_radius}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="${motor_mass}" />
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
      </inertial>
    </link>

    <joint name="${prefix}_ankle_motor_mount" type="fixed">
      <parent link="${prefix}_shank" />
      <child link="${prefix}_ankle_motor" />
      <origin xyz="0 0 -${shank_length}" rpy="0 0 0" /> <!-- No rotation here -->
    </joint>

    <joint name="${prefix}_ankle_joint" type="revolute">
      <parent link="${prefix}_ankle_motor" />
      <child link="${prefix}_foot" />
      <origin xyz="0 0 -${motor_length/2}" rpy="0 0 0" /> <!-- No rotation to align foot -->
      <axis xyz="0 1 0" />
      <limit effort="5" velocity="2.0" lower="-2.0" upper="2.0" />
    </joint>

    <link name="${prefix}_foot">
      <visual>
        <geometry>
          <sphere radius="${foot_radius}" />
        </geometry>
        <material name="black" />
      </visual>
      <collision>
        <geometry>
          <sphere radius="${foot_radius}" />
        </geometry>
      </collision>
      <xacro:inertial_sphere mass="0.1" radius="${foot_radius}" />
    </link>

    <!-- Gazebo settings for foot friction -->
    <gazebo reference="${prefix}_foot">
      <mu1>0.8</mu1>
      <mu2>0.8</mu2>
    </gazebo>

    <!-- Transmissions -->
    <transmission name="${prefix}_hip_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_hip_joint" />
      <actuator name="${prefix}_hip_actuator" />
    </transmission>
    <transmission name="${prefix}_knee_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_knee_joint" />
      <actuator name="${prefix}_knee_actuator" />
    </transmission>
    <transmission name="${prefix}_ankle_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_ankle_joint" />
      <actuator name="${prefix}_ankle_actuator" />
    </transmission>

  </xacro:macro>

</robot>