<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Macro định nghĩa phần inertial (khối lượng, khối tâm, quán tính) -->
  <xacro:macro name="inertial_box" params="mass box_size">
    <inertial>
      <mass value="${mass}" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia
        ixx="${(1/12.0)*mass*(pow(box_size[1],2)+pow(box_size[2],2))}"
        iyy="${(1/12.0)*mass*(pow(box_size[0],2)+pow(box_size[2],2))}"
        izz="${(1/12.0)*mass*(pow(box_size[0],2)+pow(box_size[1],2))}"
        ixy="0.0" ixz="0.0" iyz="0.0" />
    </inertial>
  </xacro:macro>

  <!-- Macro định nghĩa một đoạn chân -->
  <xacro:macro name="leg_segment"
    params="parent_link child_link joint_name length radius xyz rpy joint_axis">
    <link name="${child_link}">
      <visual>
        <origin xyz="0 0 ${length / 2.0}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${radius}" length="${length}" />
        </geometry>
        <material name="Blue">
          <color rgba="0.1 0.1 0.8 1.0" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${length / 2.0}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${radius}" length="${length}" />
        </geometry>
      </collision>
      <xacro:inertial_box mass="0.2" box_size="${[radius*2, radius*2, length]}" />
    </link>

    <joint name="${joint_name}" type="continuous">
      <parent link="${parent_link}" />
      <child link="${child_link}" />
      <origin xyz="${xyz}" rpy="${rpy}" />
      <axis xyz="${joint_axis}" />
      <limit effort="5.0" velocity="2.0" />
    </joint>

    <transmission name="${joint_name}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${joint_name}">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="${joint_name}_motor">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <!-- Macro định nghĩa chân hoàn chỉnh gồm 2 khớp: hip và knee -->
  <xacro:macro name="leg" params="side pos suffix base_link hip_pos hip_rpy knee_pos knee_rpy ankle_pos ankle_rpy">
    <!-- Hip segment -->
    <xacro:leg_segment
      parent_link="${base_link}"
      child_link="${side}_${pos}_hip_link${suffix}"
      joint_name="${side}_${pos}_hip_joint${suffix}"
      length="0.05"
      radius="0.02"
      xyz="${hip_pos}"
      rpy="${hip_rpy}"
      joint_axis="0 1 0" />

    <!-- Knee segment -->
    <xacro:leg_segment
      parent_link="${side}_${pos}_hip_link${suffix}"
      child_link="${side}_${pos}_knee_link${suffix}"
      joint_name="${side}_${pos}_knee_joint${suffix}"
      length="0.08"
      radius="0.015"
      xyz="${knee_pos}"
      rpy="${knee_rpy}"
      joint_axis="0 1 0" />

    <!-- Ankle segment -->
    <xacro:leg_segment
      parent_link="${side}_${pos}_knee_link${suffix}"
      child_link="${side}_${pos}_ankle_link${suffix}"
      joint_name="${side}_${pos}_ankle_joint${suffix}"
      length="0.05"
      radius="0.015"
      xyz="${ankle_pos}"
      rpy="${ankle_rpy}"
      joint_axis="0 1 0" />
  </xacro:macro>

</robot>