<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="thigh_length" value="0.18" /> <!-- Length of thigh link m -->
  <xacro:property name="shank_length" value="0.18" /> <!-- Length of shank link m -->
  <xacro:property name="motor_mass" value="0.03" /> <!-- Mass of motor links kg -->
  <xacro:property name="motor_radius" value="0.012" /> <!-- Radius of motor cylinders m -->
  <xacro:property name="motor_length" value="0.02" /> <!-- Length of motor cylinders m -->
  <xacro:property name="foot_radius" value="0.03" /> <!-- Radius of foot sphere m -->

  <!--  INERTIAL MACRO  -->
  <!-- Macro to calculate inertia for box-shaped links -->
  <xacro:macro name="inertial_box_leg" params="mass box_size">
    <inertial>
      <mass value="${mass}" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia
        ixx="${(1/12.0)*mass*(pow(box_size[1],2)+pow(box_size[2],2))}"
        iyy="${(1/12.0)*mass*(pow(box_size[0],2)+pow(box_size[2],2))}"
        izz="${(1/12.0)*mass*(pow(box_size[0],2)+pow(box_size[1],2))}"
        ixy="0.0" ixz="0.0" iyz="0.0" />
    </inertial>
  </xacro:macro>

  <!--  LEG MACRO  -->
  <!-- Macro to define a single leg with hip thigh knee shank ankle and foot -->
  <xacro:macro name="leg" params="prefix x y">

    <!--  HIP SECTION  -->
    <!-- Hip motor link  Small cylindrical motor attached to chassis -->
    <link name="${prefix}_hip_motor">
      <visual>
        <origin xyz="0 0 0.005" />
        <geometry>
          <cylinder length="${motor_length}" radius="${motor_radius}" />
        </geometry>
        <material name="grey" />
      </visual>
      <collision>
        <origin xyz="0 0 0.005" />
        <geometry>
          <cylinder length="${motor_length}" radius="${motor_radius}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="${motor_mass}" />
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
      </inertial>
    </link>

    <!-- Hip motor mount  Fixed joint attaching hip motor to chassis -->
    <joint name="${prefix}_hip_motor_mount" type="fixed">
      <parent link="chassis" />
      <child link="${prefix}_hip_motor" />
      <origin xyz="${x} ${y} -0.005" />
    </joint>

    <!-- Hip joint  Revolute joint for thigh rotation, limited to forward motion -->
    <joint name="${prefix}_hip_joint" type="revolute">
      <parent link="${prefix}_hip_motor" />
      <child link="${prefix}_thigh" />
      <origin xyz="0 0 0" />
      <axis xyz="0 1 0" /> <!-- Rotation around y-axis -->
      <limit effort="5" velocity="2.0" lower="-1.57" upper="0" /> <!-- Forward motion only -->
    </joint>

    <!-- Thigh link  Box-shaped link connecting hip to knee -->
    <link name="${prefix}_thigh">
      <visual>
        <origin xyz="0 0 -${thigh_length/2}" /> <!-- Center of thigh -->
        <geometry>
          <box size="0.03 0.03 ${thigh_length}" />
        </geometry>
        <material name="blue" />
      </visual>
      <collision>
        <origin xyz="0 0 -${thigh_length/2}" />
        <geometry>
          <box size="0.03 0.03 ${thigh_length}" />
        </geometry>
      </collision>
      <xacro:inertial_box_leg mass="0.15" box_size="${[0.03, 0.03, thigh_length]}" />
    </link>

    <!--  KNEE SECTION  -->
    <!-- Knee motor link  Small cylindrical motor attached to thigh -->
    <link name="${prefix}_knee_motor">
      <visual>
        <origin xyz="0 0 -0.01" />
        <geometry>
          <cylinder length="${motor_length}" radius="${motor_radius}" />
        </geometry>
        <material name="grey" />
      </visual>
      <collision>
        <origin xyz="0 0 -0.01" />
        <geometry>
          <cylinder length="${motor_length}" radius="${motor_radius}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="${motor_mass}" />
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
      </inertial>
    </link>

    <!-- Knee motor mount  Fixed joint attaching knee motor to thigh -->
    <joint name="${prefix}_knee_motor_mount" type="fixed">
      <parent link="${prefix}_thigh" />
      <child link="${prefix}_knee_motor" />
      <origin xyz="0 0 -${thigh_length}" rpy="0 -0.3 0" /> <!-- Tilt forward for natural posture -->
    </joint>

    <!-- Knee joint  Revolute joint for shank rotation, limited to forward motion -->
    <joint name="${prefix}_knee_joint" type="revolute">
      <parent link="${prefix}_knee_motor" />
      <child link="${prefix}_shank" />
      <origin xyz="0 0 0" />
      <axis xyz="0 1 0" /> <!-- Rotation around y axis -->
      <limit effort="5" velocity="2.0" lower="-2.5" upper="0" /> <!-- Forward motion only -->
    </joint>

    <!-- Shank link  Box-shaped link connecting knee to ankle -->
    <link name="${prefix}_shank">
      <visual>
        <origin xyz="0 0 -${shank_length/2}" />
        <geometry>
          <box size="0.02 0.02 ${shank_length}" />
        </geometry>
        <material name="red" />
      </visual>
      <collision>
        <origin xyz="0 0 -${shank_length/2}" />
        <geometry>
          <box size="0.02 0.02 ${shank_length}" />
        </geometry>
      </collision>
      <xacro:inertial_box_leg mass="0.15" box_size="${[0.02, 0.02, shank_length]}" />
    </link>

    <!--  ANKLE SECTION  -->
    <!-- Ankle motor link  Small cylindrical motor attached to shank -->
    <link name="${prefix}_ankle_motor">
      <visual>
        <origin xyz="0 0 -0.01" />
        <geometry>
          <cylinder length="${motor_length}" radius="${motor_radius}" />
        </geometry>
        <material name="grey" />
      </visual>
      <collision>
        <origin xyz="0 0 -0.01" />
        <geometry>
          <cylinder length="${motor_length}" radius="${motor_radius}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="${motor_mass}" />
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
      </inertial>
    </link>

    <!-- Ankle motor mount  Fixed joint attaching ankle motor to shank -->
    <joint name="${prefix}_ankle_motor_mount" type="fixed">
      <parent link="${prefix}_shank" />
      <child link="${prefix}_ankle_motor" />
      <origin xyz="0 0 -${shank_length}" rpy="0 -0.3 0" /> <!-- Tilt forward for natural posture -->
    </joint>

    <!-- Ankle joint  Revolute joint for foot rotation -->
    <joint name="${prefix}_ankle_joint" type="revolute">
      <parent link="${prefix}_ankle_motor" />
      <child link="${prefix}_foot" />
      <origin xyz="0 0 0" />
      <axis xyz="0 1 0" /> <!-- Rotation around y-axis -->
      <limit effort="5" velocity="2.0" lower="-2.0" upper="2.0" />
    </joint>

    <!-- Foot link  Spherical foot for ground contact -->
    <link name="${prefix}_foot">
      <visual>
        <geometry>
          <sphere radius="${foot_radius}" />
        </geometry>
        <material name="black" />
      </visual>
      <collision>
        <geometry>
          <sphere radius="${foot_radius}" />
        </geometry>
      </collision>
      <xacro:inertial_sphere mass="0.1" radius="${foot_radius}">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:inertial_sphere>
    </link>

    <!-- Gazebo settings for foot friction -->
    <gazebo reference="${prefix}_foot">
      <mu1>0.8</mu1> <!-- Giảm ma sát ngang -->
      <mu2>0.8</mu2> <!-- Giảm ma sát dọc -->
    </gazebo>


    <transmission name="${prefix}_hip_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_hip_joint" />
      <actuator name="${prefix}_hip_actuator" />
    </transmission>
    <transmission name="${prefix}_knee_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_knee_joint" />
      <actuator name="${prefix}_knee_actuator" />
    </transmission>
    <transmission name="${prefix}_ankle_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_ankle_joint" />
      <actuator name="${prefix}_ankle_actuator" />
    </transmission>

  </xacro:macro>

</robot>